export { default as About } from './About'
export { default as DetailsWorks } from './DetailsWorks'
export { default as Contact } from './Contact'
export { default as Expertises } from './Expertises'
export { default as Works } from './Works'
