export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Educations } from './Educations'
export { default as Experiences } from './Experiences'
export { default as Expertises } from './Expertises'
export { default as Works } from './Works'
